Stc\ScraperBundle\Entity\Entity:
    type: entity
    table: entity
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        desc:
            type: string
            length: 255
        name:
            type: string
            length: 30
        is_active:
            type: string
            length: 1
        created_at:
            type: datetime
        updated_at:
            type: datetime
    oneToMany:
        websites:
            targetEntity: Website
            mappedBy: entity_id
        website_entities:
            targetEntity: WebsiteEntity
            mappedBy: entity_id
    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue ]
        preUpdate:  [ setUpdatedAtValue ]