Stc\ScraperBundle\Entity\WebsiteEntity:
    type: entity
    table: website_entity
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    manyToOne:
        entity:
            targetEntity: Entity
            inversedBy: website_entities
            joinColumn:
                name: id
                referencedColumnName: id
        website:
            targetEntity: Website
            inversedBy: website_entities
            joincolumn:
                name: website_id
                referencedColumnName: id