Stc\ScraperBundle\Entity\Website:
    type: entity
    table: websites
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        url:
            type: string
            length: 100
            unique: true
        entity_id:
            type: integer
            length: 10
        is_active:
            type: string
            length: 1
        created_at:
            type: datetime
        updated_at:
            type: datetime
    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue ]
        preUpdate:  [ setUpdatedAtValue ]