Stc\ScraperBundle\Entity\YelpContent:
    type: entity
    table: yelp_content
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        entity_id:
            type: integer
            length: 10
        name:
            type: string
            length: 100
        url:
            type: string
            length: 255
            unique: true
        is_active:
            type: string
            length: 1
        created_at:
            type: datetime
        updated_at:
            type: datetime
    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue ]
        preUpdate:  [ setUpdatedAtValue ]