stc_scraper_homepage:
    pattern:  /
    defaults: { _controller: StcScraperBundle:Default:index }

stc_scraper_create:
    pattern: /create
    defaults:  { _controller: StcScraperBundle:Default:create }