stc_scraper_homepage:
    pattern:  /
    defaults: { _controller: StcScraperBundle:Default:index }

stc_scraper_form_entity_submit:
  pattern:  /insert/entity
  defaults: { _controller: StcScraperBundle:Default:post }

stc_scraper_form_basesite_submit:
  pattern: /select/basesite
  defaults: { _controller: StcScraperBundle:Default:start }